### ISSUE TITLE
你好 我想 修改一下 图片轮播的速度  不是时间间隔，  我能在哪里设置？

### ISSUE THREAD

**Issue by GGjin** [yuanhoujun/AutoScrollViewPager#1]
这个目前没有提供api，需要这方面的api吗？

**Comment by yuanhoujun** [comment]
版本更新到1.0.1，已经增加这个api了，可以在xml中指定app:scrollFactor="2.0",可以调用setScrollFactor方法设置，这个值越大，速度就越慢。

**Comment by GGjin** [comment]
好的 谢谢
